#!/bin/sh
echo -e "\n##########################################"
echo -e   "#                                        #"
echo -e   "# Let's check domains from domains file  #"
echo -e   "# Count number of                        #"
echo -e   "# SUCCESS codes for each domain          #"
echo -e   "# Output should be sorted by number of   #"
echo -e   "# SUCCESS codes                          #"
echo -e   "# <domain>:<number of SUCCESS codes>     #"
echo -e   "# E.g.:                                  #"
echo -e   "#  amogus.ru:2                           #"
echo -e   "#  qwe.qwe:4                             #"
echo -e   "#  sample.net:6                          #"
echo -e   "#                                        #"
echo -e   "#  Let's curl again                      #"
echo -e   "#  like we did last summer               #"
echo -e   "#                                        #"
echo -e   "##########################################"
